### ISSUE TITLE
Virtual fields not present on client-side document object

### ISSUE THREAD

**Issue by mathiasm74** [BeekeeperAlex/mongoose-simpledb#4]
Not sure if this is a defect or if I'm just missing something but...

I have a User schema that looks like this:

```
exports.schema = {
    name: {
        first: { type: String, trim: true },
        last: { type: String, trim: true }
    }
}

exports.virtuals = {
    full_name: {
        get: function () {
            return this.name.first + ' ' + this.name.last;
        }
    }
}
```

The virtual "full_name" field works fine on the node side, but when I get a document of this type on the client side the virtual field is not present:

```
var user = db.User.get({ id: $routeParams.id });
console.log(user.name.first); // works
console.log(user.full_name); // doesn't work (prints Undefined)
```

**Comment by piyushpatel2005** [comment]
It is really difficult to work without virtuals. For example, I have a situation in which  I have two models user and tutorial.
```javascript
tutorialSchema = new Schema({
    owner: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }]
});
```

```javascript
userSchema = new Schema({
    first: {
        type: String
    },
    last: {
        type: String
    }
});

userSchema.virtual('fullname').get(function () {
    return this.first + ' '  + this.last;
});
```
Now, when I send tutorial from the backend to the front end *with owner populated*, I get virtuals for tutorialSchema but not userSchema even if I have used toJSON defined with `virtuals: true`.
